package ifactory.module.report;

import java.util.Date;

public class Secclockrecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secclockrecord.id
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secclockrecord.companycode
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */
	private String companycode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secclockrecord.cmd
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */
	private String cmd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secclockrecord.serectId
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */
	private String serectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secclockrecord.rfid
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */
	private String rfid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secclockrecord.sTime
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */
	private Date sTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secclockrecord.eTime
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */
	private Date eTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secclockrecord.id
	 * @return  the value of secclockrecord.id
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secclockrecord.id
	 * @param id  the value for secclockrecord.id
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secclockrecord.companycode
	 * @return  the value of secclockrecord.companycode
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */
	public String getCompanycode() {
		return companycode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secclockrecord.companycode
	 * @param companycode  the value for secclockrecord.companycode
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */
	public void setCompanycode(String companycode) {
		this.companycode = companycode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secclockrecord.cmd
	 * @return  the value of secclockrecord.cmd
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */
	public String getCmd() {
		return cmd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secclockrecord.cmd
	 * @param cmd  the value for secclockrecord.cmd
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */
	public void setCmd(String cmd) {
		this.cmd = cmd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secclockrecord.serectId
	 * @return  the value of secclockrecord.serectId
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */
	public String getSerectId() {
		return serectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secclockrecord.serectId
	 * @param serectId  the value for secclockrecord.serectId
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */
	public void setSerectId(String serectId) {
		this.serectId = serectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secclockrecord.rfid
	 * @return  the value of secclockrecord.rfid
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */
	public String getRfid() {
		return rfid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secclockrecord.rfid
	 * @param rfid  the value for secclockrecord.rfid
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */
	public void setRfid(String rfid) {
		this.rfid = rfid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secclockrecord.sTime
	 * @return  the value of secclockrecord.sTime
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */
	public Date getsTime() {
		return sTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secclockrecord.sTime
	 * @param sTime  the value for secclockrecord.sTime
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */
	public void setsTime(Date sTime) {
		this.sTime = sTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secclockrecord.eTime
	 * @return  the value of secclockrecord.eTime
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */
	public Date geteTime() {
		return eTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secclockrecord.eTime
	 * @param eTime  the value for secclockrecord.eTime
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */
	public void seteTime(Date eTime) {
		this.eTime = eTime;
	}
}