package ifactory.module.report;

import ifactory.module.report.Secclockrecord;
import ifactory.module.report.SecclockrecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecclockrecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table secclockrecord
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */
	long countByExample(SecclockrecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table secclockrecord
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */
	int deleteByExample(SecclockrecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table secclockrecord
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table secclockrecord
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */
	int insert(Secclockrecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table secclockrecord
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */
	int insertSelective(Secclockrecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table secclockrecord
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */List<Secclockrecord> selectByExample(SecclockrecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table secclockrecord
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */
	Secclockrecord selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table secclockrecord
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */int updateByExampleSelective(@Param("record") Secclockrecord record,@Param("example") SecclockrecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table secclockrecord
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */int updateByExample(@Param("record") Secclockrecord record,@Param("example") SecclockrecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table secclockrecord
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */
	int updateByPrimaryKeySelective(Secclockrecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table secclockrecord
	 * @mbg.generated  Wed Dec 20 11:42:53 CST 2017
	 */
	int updateByPrimaryKey(Secclockrecord record);
}