package ifactory.module.statistics;

import java.util.Date;

public class Sectimesum {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secTimeSum.id
	 * @mbg.generated  Thu Dec 28 18:56:11 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secTimeSum.companycode
	 * @mbg.generated  Thu Dec 28 18:56:11 CST 2017
	 */
	private String companycode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secTimeSum.sumType
	 * @mbg.generated  Thu Dec 28 18:56:11 CST 2017
	 */
	private String sumType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secTimeSum.startTime
	 * @mbg.generated  Thu Dec 28 18:56:11 CST 2017
	 */
	private Date startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secTimeSum.endTime
	 * @mbg.generated  Thu Dec 28 18:56:11 CST 2017
	 */
	private Date endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secTimeSum.rfid
	 * @mbg.generated  Thu Dec 28 18:56:11 CST 2017
	 */
	private String rfid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secTimeSum.realTime
	 * @mbg.generated  Thu Dec 28 18:56:11 CST 2017
	 */
	private String realTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secTimeSum.id
	 * @return  the value of secTimeSum.id
	 * @mbg.generated  Thu Dec 28 18:56:11 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secTimeSum.id
	 * @param id  the value for secTimeSum.id
	 * @mbg.generated  Thu Dec 28 18:56:11 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secTimeSum.companycode
	 * @return  the value of secTimeSum.companycode
	 * @mbg.generated  Thu Dec 28 18:56:11 CST 2017
	 */
	public String getCompanycode() {
		return companycode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secTimeSum.companycode
	 * @param companycode  the value for secTimeSum.companycode
	 * @mbg.generated  Thu Dec 28 18:56:11 CST 2017
	 */
	public void setCompanycode(String companycode) {
		this.companycode = companycode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secTimeSum.sumType
	 * @return  the value of secTimeSum.sumType
	 * @mbg.generated  Thu Dec 28 18:56:11 CST 2017
	 */
	public String getSumType() {
		return sumType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secTimeSum.sumType
	 * @param sumType  the value for secTimeSum.sumType
	 * @mbg.generated  Thu Dec 28 18:56:11 CST 2017
	 */
	public void setSumType(String sumType) {
		this.sumType = sumType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secTimeSum.startTime
	 * @return  the value of secTimeSum.startTime
	 * @mbg.generated  Thu Dec 28 18:56:11 CST 2017
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secTimeSum.startTime
	 * @param startTime  the value for secTimeSum.startTime
	 * @mbg.generated  Thu Dec 28 18:56:11 CST 2017
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secTimeSum.endTime
	 * @return  the value of secTimeSum.endTime
	 * @mbg.generated  Thu Dec 28 18:56:11 CST 2017
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secTimeSum.endTime
	 * @param endTime  the value for secTimeSum.endTime
	 * @mbg.generated  Thu Dec 28 18:56:11 CST 2017
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secTimeSum.rfid
	 * @return  the value of secTimeSum.rfid
	 * @mbg.generated  Thu Dec 28 18:56:11 CST 2017
	 */
	public String getRfid() {
		return rfid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secTimeSum.rfid
	 * @param rfid  the value for secTimeSum.rfid
	 * @mbg.generated  Thu Dec 28 18:56:11 CST 2017
	 */
	public void setRfid(String rfid) {
		this.rfid = rfid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secTimeSum.realTime
	 * @return  the value of secTimeSum.realTime
	 * @mbg.generated  Thu Dec 28 18:56:11 CST 2017
	 */
	public String getRealTime() {
		return realTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secTimeSum.realTime
	 * @param realTime  the value for secTimeSum.realTime
	 * @mbg.generated  Thu Dec 28 18:56:11 CST 2017
	 */
	public void setRealTime(String realTime) {
		this.realTime = realTime;
	}
}