package ifactory.module.employee;

import ifactory.module.employee.Sysemployee;
import ifactory.module.employee.SysemployeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysemployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysemployee
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    long countByExample(SysemployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysemployee
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    int deleteByExample(SysemployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysemployee
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysemployee
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    int insert(Sysemployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysemployee
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    int insertSelective(Sysemployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysemployee
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    List<Sysemployee> selectByExample(SysemployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysemployee
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    Sysemployee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysemployee
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    int updateByExampleSelective(@Param("record") Sysemployee record, @Param("example") SysemployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysemployee
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    int updateByExample(@Param("record") Sysemployee record, @Param("example") SysemployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysemployee
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    int updateByPrimaryKeySelective(Sysemployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysemployee
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    int updateByPrimaryKey(Sysemployee record);
}