package ifactory.module.employee;

public class Sysemployee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysemployee.id
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysemployee.companycode
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    private String companycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysemployee.rfid
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    private String rfid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysemployee.jobNumber
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    private String jobNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysemployee.name
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysemployee.factroy
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    private String factroy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysemployee.department
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    private String department;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysemployee.id
     *
     * @return the value of sysemployee.id
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysemployee.id
     *
     * @param id the value for sysemployee.id
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysemployee.companycode
     *
     * @return the value of sysemployee.companycode
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    public String getCompanycode() {
        return companycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysemployee.companycode
     *
     * @param companycode the value for sysemployee.companycode
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    public void setCompanycode(String companycode) {
        this.companycode = companycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysemployee.rfid
     *
     * @return the value of sysemployee.rfid
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    public String getRfid() {
        return rfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysemployee.rfid
     *
     * @param rfid the value for sysemployee.rfid
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    public void setRfid(String rfid) {
        this.rfid = rfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysemployee.jobNumber
     *
     * @return the value of sysemployee.jobNumber
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    public String getJobNumber() {
        return jobNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysemployee.jobNumber
     *
     * @param jobNumber the value for sysemployee.jobNumber
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    public void setJobNumber(String jobNumber) {
        this.jobNumber = jobNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysemployee.name
     *
     * @return the value of sysemployee.name
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysemployee.name
     *
     * @param name the value for sysemployee.name
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysemployee.factroy
     *
     * @return the value of sysemployee.factroy
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    public String getFactroy() {
        return factroy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysemployee.factroy
     *
     * @param factroy the value for sysemployee.factroy
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    public void setFactroy(String factroy) {
        this.factroy = factroy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysemployee.department
     *
     * @return the value of sysemployee.department
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysemployee.department
     *
     * @param department the value for sysemployee.department
     *
     * @mbg.generated Sat Dec 09 16:28:19 CST 2017
     */
    public void setDepartment(String department) {
        this.department = department;
    }
}