package ifactory.module.call;

import java.util.Date;

public class Callrecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column callRecord.id
	 * @mbg.generated  Fri Dec 29 11:11:58 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column callRecord.rfid
	 * @mbg.generated  Fri Dec 29 11:11:58 CST 2017
	 */
	private String rfid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column callRecord.callTime
	 * @mbg.generated  Fri Dec 29 11:11:58 CST 2017
	 */
	private Date callTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column callRecord.callType
	 * @mbg.generated  Fri Dec 29 11:11:58 CST 2017
	 */
	private String callType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column callRecord.secretKey
	 * @mbg.generated  Fri Dec 29 11:11:58 CST 2017
	 */
	private String secretKey;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column callRecord.id
	 * @return  the value of callRecord.id
	 * @mbg.generated  Fri Dec 29 11:11:58 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column callRecord.id
	 * @param id  the value for callRecord.id
	 * @mbg.generated  Fri Dec 29 11:11:58 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column callRecord.rfid
	 * @return  the value of callRecord.rfid
	 * @mbg.generated  Fri Dec 29 11:11:58 CST 2017
	 */
	public String getRfid() {
		return rfid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column callRecord.rfid
	 * @param rfid  the value for callRecord.rfid
	 * @mbg.generated  Fri Dec 29 11:11:58 CST 2017
	 */
	public void setRfid(String rfid) {
		this.rfid = rfid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column callRecord.callTime
	 * @return  the value of callRecord.callTime
	 * @mbg.generated  Fri Dec 29 11:11:58 CST 2017
	 */
	public Date getCallTime() {
		return callTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column callRecord.callTime
	 * @param callTime  the value for callRecord.callTime
	 * @mbg.generated  Fri Dec 29 11:11:58 CST 2017
	 */
	public void setCallTime(Date callTime) {
		this.callTime = callTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column callRecord.callType
	 * @return  the value of callRecord.callType
	 * @mbg.generated  Fri Dec 29 11:11:58 CST 2017
	 */
	public String getCallType() {
		return callType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column callRecord.callType
	 * @param callType  the value for callRecord.callType
	 * @mbg.generated  Fri Dec 29 11:11:58 CST 2017
	 */
	public void setCallType(String callType) {
		this.callType = callType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column callRecord.secretKey
	 * @return  the value of callRecord.secretKey
	 * @mbg.generated  Fri Dec 29 11:11:58 CST 2017
	 */
	public String getSecretKey() {
		return secretKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column callRecord.secretKey
	 * @param secretKey  the value for callRecord.secretKey
	 * @mbg.generated  Fri Dec 29 11:11:58 CST 2017
	 */
	public void setSecretKey(String secretKey) {
		this.secretKey = secretKey;
	}
}