package ifactory.module.secretary;

public class Secretary {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secretary.id
	 * @mbg.generated  Thu Dec 28 14:36:51 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secretary.deviceId
	 * @mbg.generated  Thu Dec 28 14:36:51 CST 2017
	 */
	private String deviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secretary.secretKey
	 * @mbg.generated  Thu Dec 28 14:36:51 CST 2017
	 */
	private String secretKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secretary.companyCode
	 * @mbg.generated  Thu Dec 28 14:36:51 CST 2017
	 */
	private String companyCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secretary.factory
	 * @mbg.generated  Thu Dec 28 14:36:51 CST 2017
	 */
	private String factory;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secretary.department
	 * @mbg.generated  Thu Dec 28 14:36:51 CST 2017
	 */
	private String department;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secretary.alias
	 * @mbg.generated  Thu Dec 28 14:36:51 CST 2017
	 */
	private String alias;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secretary.state
	 * @mbg.generated  Thu Dec 28 14:36:51 CST 2017
	 */
	private String state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secretary.receivedType
	 * @mbg.generated  Thu Dec 28 14:36:51 CST 2017
	 */
	private String receivedType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secretary.station
	 * @mbg.generated  Thu Dec 28 14:36:51 CST 2017
	 */
	private String station;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secretary.id
	 * @return  the value of secretary.id
	 * @mbg.generated  Thu Dec 28 14:36:51 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secretary.id
	 * @param id  the value for secretary.id
	 * @mbg.generated  Thu Dec 28 14:36:51 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secretary.deviceId
	 * @return  the value of secretary.deviceId
	 * @mbg.generated  Thu Dec 28 14:36:51 CST 2017
	 */
	public String getDeviceId() {
		return deviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secretary.deviceId
	 * @param deviceId  the value for secretary.deviceId
	 * @mbg.generated  Thu Dec 28 14:36:51 CST 2017
	 */
	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secretary.secretKey
	 * @return  the value of secretary.secretKey
	 * @mbg.generated  Thu Dec 28 14:36:51 CST 2017
	 */
	public String getSecretKey() {
		return secretKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secretary.secretKey
	 * @param secretKey  the value for secretary.secretKey
	 * @mbg.generated  Thu Dec 28 14:36:51 CST 2017
	 */
	public void setSecretKey(String secretKey) {
		this.secretKey = secretKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secretary.companyCode
	 * @return  the value of secretary.companyCode
	 * @mbg.generated  Thu Dec 28 14:36:51 CST 2017
	 */
	public String getCompanyCode() {
		return companyCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secretary.companyCode
	 * @param companyCode  the value for secretary.companyCode
	 * @mbg.generated  Thu Dec 28 14:36:51 CST 2017
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secretary.factory
	 * @return  the value of secretary.factory
	 * @mbg.generated  Thu Dec 28 14:36:51 CST 2017
	 */
	public String getFactory() {
		return factory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secretary.factory
	 * @param factory  the value for secretary.factory
	 * @mbg.generated  Thu Dec 28 14:36:51 CST 2017
	 */
	public void setFactory(String factory) {
		this.factory = factory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secretary.department
	 * @return  the value of secretary.department
	 * @mbg.generated  Thu Dec 28 14:36:51 CST 2017
	 */
	public String getDepartment() {
		return department;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secretary.department
	 * @param department  the value for secretary.department
	 * @mbg.generated  Thu Dec 28 14:36:51 CST 2017
	 */
	public void setDepartment(String department) {
		this.department = department;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secretary.alias
	 * @return  the value of secretary.alias
	 * @mbg.generated  Thu Dec 28 14:36:51 CST 2017
	 */
	public String getAlias() {
		return alias;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secretary.alias
	 * @param alias  the value for secretary.alias
	 * @mbg.generated  Thu Dec 28 14:36:51 CST 2017
	 */
	public void setAlias(String alias) {
		this.alias = alias;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secretary.state
	 * @return  the value of secretary.state
	 * @mbg.generated  Thu Dec 28 14:36:51 CST 2017
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secretary.state
	 * @param state  the value for secretary.state
	 * @mbg.generated  Thu Dec 28 14:36:51 CST 2017
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secretary.receivedType
	 * @return  the value of secretary.receivedType
	 * @mbg.generated  Thu Dec 28 14:36:51 CST 2017
	 */
	public String getReceivedType() {
		return receivedType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secretary.receivedType
	 * @param receivedType  the value for secretary.receivedType
	 * @mbg.generated  Thu Dec 28 14:36:51 CST 2017
	 */
	public void setReceivedType(String receivedType) {
		this.receivedType = receivedType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secretary.station
	 * @return  the value of secretary.station
	 * @mbg.generated  Thu Dec 28 14:36:51 CST 2017
	 */
	public String getStation() {
		return station;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secretary.station
	 * @param station  the value for secretary.station
	 * @mbg.generated  Thu Dec 28 14:36:51 CST 2017
	 */
	public void setStation(String station) {
		this.station = station;
	}
}