package ifactory.module.push;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import ifactory.module.push.Secsubscription;
import ifactory.module.push.SecsubscriptionExample;

public interface SecsubscriptionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table secsubscription
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	long countByExample(SecsubscriptionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table secsubscription
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	int deleteByExample(SecsubscriptionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table secsubscription
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table secsubscription
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	int insert(Secsubscription record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table secsubscription
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	int insertSelective(Secsubscription record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table secsubscription
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */List<Secsubscription> selectByExample(SecsubscriptionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table secsubscription
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	Secsubscription selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table secsubscription
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */int updateByExampleSelective(@Param("record") Secsubscription record,@Param("example") SecsubscriptionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table secsubscription
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */int updateByExample(@Param("record") Secsubscription record,@Param("example") SecsubscriptionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table secsubscription
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	int updateByPrimaryKeySelective(Secsubscription record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table secsubscription
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	int updateByPrimaryKey(Secsubscription record);
}