package ifactory.module.push;

public class Secsubscription {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secsubscription.id
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secsubscription.companyCode
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	private String companyCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secsubscription.userId
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secsubscription.type
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secsubscription.deviceId
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	private String deviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secsubscription.secretKey
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	private String secretKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secsubscription.department
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	private String department;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secsubscription.alias
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	private String alias;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secsubscription.station
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	private String station;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column secsubscription.factory
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	private String factory;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secsubscription.id
	 * @return  the value of secsubscription.id
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secsubscription.id
	 * @param id  the value for secsubscription.id
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secsubscription.companyCode
	 * @return  the value of secsubscription.companyCode
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	public String getCompanyCode() {
		return companyCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secsubscription.companyCode
	 * @param companyCode  the value for secsubscription.companyCode
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secsubscription.userId
	 * @return  the value of secsubscription.userId
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secsubscription.userId
	 * @param userId  the value for secsubscription.userId
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secsubscription.type
	 * @return  the value of secsubscription.type
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secsubscription.type
	 * @param type  the value for secsubscription.type
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secsubscription.deviceId
	 * @return  the value of secsubscription.deviceId
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	public String getDeviceId() {
		return deviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secsubscription.deviceId
	 * @param deviceId  the value for secsubscription.deviceId
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secsubscription.secretKey
	 * @return  the value of secsubscription.secretKey
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	public String getSecretKey() {
		return secretKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secsubscription.secretKey
	 * @param secretKey  the value for secsubscription.secretKey
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	public void setSecretKey(String secretKey) {
		this.secretKey = secretKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secsubscription.department
	 * @return  the value of secsubscription.department
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	public String getDepartment() {
		return department;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secsubscription.department
	 * @param department  the value for secsubscription.department
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	public void setDepartment(String department) {
		this.department = department;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secsubscription.alias
	 * @return  the value of secsubscription.alias
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	public String getAlias() {
		return alias;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secsubscription.alias
	 * @param alias  the value for secsubscription.alias
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	public void setAlias(String alias) {
		this.alias = alias;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secsubscription.station
	 * @return  the value of secsubscription.station
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	public String getStation() {
		return station;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secsubscription.station
	 * @param station  the value for secsubscription.station
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	public void setStation(String station) {
		this.station = station;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column secsubscription.factory
	 * @return  the value of secsubscription.factory
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	public String getFactory() {
		return factory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column secsubscription.factory
	 * @param factory  the value for secsubscription.factory
	 * @mbg.generated  Thu Dec 28 14:54:10 CST 2017
	 */
	public void setFactory(String factory) {
		this.factory = factory;
	}
}