package ifactory.module.worker;

public class Worker {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column worker.id
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column worker.deviceId
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	private String deviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column worker.secretKey
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	private String secretKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column worker.company
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	private String company;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column worker.department
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	private String department;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column worker.companyCode
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	private String companyCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column worker.alias
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	private String alias;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column worker.stationCode
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	private String stationCode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column worker.id
	 * @return  the value of worker.id
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column worker.id
	 * @param id  the value for worker.id
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column worker.deviceId
	 * @return  the value of worker.deviceId
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	public String getDeviceId() {
		return deviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column worker.deviceId
	 * @param deviceId  the value for worker.deviceId
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column worker.secretKey
	 * @return  the value of worker.secretKey
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	public String getSecretKey() {
		return secretKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column worker.secretKey
	 * @param secretKey  the value for worker.secretKey
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	public void setSecretKey(String secretKey) {
		this.secretKey = secretKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column worker.company
	 * @return  the value of worker.company
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	public String getCompany() {
		return company;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column worker.company
	 * @param company  the value for worker.company
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	public void setCompany(String company) {
		this.company = company;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column worker.department
	 * @return  the value of worker.department
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	public String getDepartment() {
		return department;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column worker.department
	 * @param department  the value for worker.department
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	public void setDepartment(String department) {
		this.department = department;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column worker.companyCode
	 * @return  the value of worker.companyCode
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	public String getCompanyCode() {
		return companyCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column worker.companyCode
	 * @param companyCode  the value for worker.companyCode
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column worker.alias
	 * @return  the value of worker.alias
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	public String getAlias() {
		return alias;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column worker.alias
	 * @param alias  the value for worker.alias
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	public void setAlias(String alias) {
		this.alias = alias;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column worker.stationCode
	 * @return  the value of worker.stationCode
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	public String getStationCode() {
		return stationCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column worker.stationCode
	 * @param stationCode  the value for worker.stationCode
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	public void setStationCode(String stationCode) {
		this.stationCode = stationCode;
	}
}