package ifactory.module.worker;

import ifactory.module.worker.Worker;
import ifactory.module.worker.WorkerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WorkerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table worker
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	long countByExample(WorkerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table worker
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	int deleteByExample(WorkerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table worker
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table worker
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	int insert(Worker record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table worker
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	int insertSelective(Worker record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table worker
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */List<Worker> selectByExample(WorkerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table worker
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	Worker selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table worker
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */int updateByExampleSelective(@Param("record") Worker record,@Param("example") WorkerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table worker
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */int updateByExample(@Param("record") Worker record,@Param("example") WorkerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table worker
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	int updateByPrimaryKeySelective(Worker record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table worker
	 * @mbg.generated  Thu Dec 07 16:56:52 CST 2017
	 */
	int updateByPrimaryKey(Worker record);
}